apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  ports:
    - name: forward
      port: 24224
      protocol: TCP
      targetPort: 24224
  selector:
    app: fluentd
