apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch.elasticsearch.svc.cluster.local
      port 9200
      scheme https
      user elastic
      password YOUR_PASSWORD
      index_name fluentd
      type_name fluentd
    </match>
# Replace YOUR_PASSWORD with the password for your Elasticsearch instance.