<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<source>
  @type docker
  @id input_docker_logs
  @log_level debug
  @include_tags true
  @tail_container true
  @read_from_head true
  <parse>
    @type json
  </parse>
</source>

<match **>
  @type azureeventhubs_buffered
  @id output_eventhub
  @log_level debug
  connection_string "Endpoint=sb://ayanfeeventshub5303.servicebus.windows.net/;SharedAccessKeyName=access-policy1;SharedAccessKey=0DagIzBVbmgrSoHJGBerbxvDWfSe2Iq9K+AEhLk0SM8=;EntityPath=ayanfeevhub"
  eventhub_name "ayanfeevhub"
  sas_key_name "access-policy1"
  sas_key "0DagIzBVbmgrSoHJGBerbxvDWfSe2Iq9K+AEhLk0SM8="
  max_send_retries -1
  message_send_timeout 30s
  <buffer>
    @type file
    path /var/log/fluentd-buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_max_interval 30s
    retry_forever true
    chunk_limit_size 16m
    queue_limit_length 1024
  </buffer>
</match>